import { Category, CategoryMeta, MenuItem } from "./types";

export const categoryMeta: Record<Category, CategoryMeta> = {
  carrinho: { label: "Carrinho Gourmet", icon: "🛒" },
  entradinhas: { label: "Entradinhas", icon: "🥟" },
  porcoes: { label: "Mini Porções", icon: "🍝" },
  sobremesas: { label: "Sobremesas", icon: "🍨" },
  servicos: { label: "Serviços Extras", icon: "⭐" },
};

export const categoryOrder: Category[] = ["carrinho", "entradinhas", "porcoes", "sobremesas", "servicos"];

export const menuItems: MenuItem[] = [
  // Carrinho Gourmet
  {
    id: "crepe-trad",
    cat: "carrinho",
    name: "Crepe Tradicional",
    desc: "Frango com queijo, queijo, presunto com queijo, calabresa com queijo, chocolate ou dois amores.",
    price: 6.00,
    unit: "unid.",
    image: "https://images.unsplash.com/photo-1519676867240-f03562e64548?w=500&auto=format&fit=crop&q=80",
  },
  {
    id: "crepe-premium",
    cat: "carrinho",
    name: "Crepe Premium",
    desc: "Frango com queijo, presunto com queijo, queijo, calabresa com queijo, carne seca com queijo, chocolate, dois amores, Nutella ou goiabada com queijo.",
    price: 7.00,
    unit: "unid.",
    image: "https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?w=500&auto=format&fit=crop&q=80",
  },
  {
    id: "crepe-frances",
    cat: "carrinho",
    name: "Crepe Francês",
    desc: "Massa fina francesa servida com opções doces e salgadas especiais.",
    price: 15.00,
    unit: "unid.",
    image: "https://images.unsplash.com/photo-1547240248-23c21a070192?w=500&auto=format&fit=crop&q=80",
  },
  {
    id: "mini-hamburguer",
    cat: "carrinho",
    name: "Mini Hambúrguer",
    desc: "Deliciosos mini burgers com queijo derretido e pão brioche super macio.",
    price: 8.00,
    unit: "unid.",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500&auto=format&fit=crop&q=80",
  },
  {
    id: "mini-dog",
    cat: "carrinho",
    name: "Mini Dog",
    desc: "Mini hot dog prensado tradicional com molho especial artesanal.",
    price: 6.00,
    unit: "unid.",
    image: "https://images.unsplash.com/photo-1619740455993-9e612b1af08a?w=500&auto=format&fit=crop&q=80",
  },
  {
    id: "espetinhos",
    cat: "carrinho",
    name: "Espetinhos",
    desc: "Assados na hora: carne, frango, coração de frango ou queijo coalho.",
    price: 15.00,
    unit: "unid.",
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=500&auto=format&fit=crop&q=80",
  },
  {
    id: "picole",
    cat: "carrinho",
    name: "Picolé Tradicional",
    desc: "Sabores frutados e cremosos refrescantes de alta qualidade.",
    price: 4.50,
    unit: "unid.",
    image: "https://images.unsplash.com/photo-1501443762994-82bd5dace89a?w=500&auto=format&fit=crop&q=80",
  },
  {
    id: "milkshake",
    cat: "carrinho",
    name: "Milkshake",
    desc: "Copo descartável incluso. (Para copo de vidro, favor consultar valor adicional).",
    price: 15.00,
    unit: "unid.",
    image: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=500&auto=format&fit=crop&q=80",
  },
  {
    id: "pipoca-gourmet",
    cat: "carrinho",
    name: "Pipoca Gourmet",
    desc: "Pipocas doces crocantes caramelizadas com coberturas especiais.",
    price: null,
    unit: null,
    image: "https://images.unsplash.com/photo-1578849278619-e73505e9610f?w=500&auto=format&fit=crop&q=80",
  },
  {
    id: "buffet-sorvetes",
    cat: "carrinho",
    name: "Buffet de Sorvetes",
    desc: "Variedade de sabores de sorvete de massa com coberturas, granulados e confeitos.",
    price: null,
    unit: null,
    image: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=500&auto=format&fit=crop&q=80",
  },
  {
    id: "brigadeiro-colher",
    cat: "carrinho",
    name: "Brigadeiro de Colher",
    desc: "Servido quente ou frio no tacho, com granulados belgas e colheres gourmet.",
    price: null,
    unit: null,
    image: "https://images.unsplash.com/photo-1511018556340-d16986a1c194?w=500&auto=format&fit=crop&q=80",
  },
  {
    id: "pipoca-algodao",
    cat: "carrinho",
    name: "Pipoca Salgada e Algodão Doce Tradicional",
    desc: "Clássicos irresistíveis de festas infantis e eventos corporativos.",
    price: null,
    unit: null,
    image: "https://images.unsplash.com/photo-1505686994434-e3cc5abf1330?w=500&auto=format&fit=crop&q=80",
  },
  {
    id: "algodao-artistico",
    cat: "carrinho",
    name: "Algodão Doce Artístico",
    desc: "Algodão doce esculpido em formatos lúdicos e multicoloridos.",
    price: null,
    unit: null,
    image: "https://images.unsplash.com/photo-1569864358642-9d1684040f43?w=500&auto=format&fit=crop&q=80",
  },
  {
    id: "cascata-chocolate",
    cat: "carrinho",
    name: "Cascata de Chocolate",
    desc: "Cascata com chocolate nobre e frutas frescas da estação para mergulhar.",
    price: null,
    unit: null,
    image: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=500&auto=format&fit=crop&q=80",
  },

  // Entradinhas
  {
    id: "canapes",
    cat: "entradinhas",
    name: "Canapés finos",
    desc: "Sabores: Ervas finas · linguiça, parma e figo · cream cheese e geleia de pimenta · tomate seco e rúcula.",
    price: 6.00,
    unit: "unid.",
    image: "https://images.unsplash.com/photo-1541532713592-79a0317b6b77?w=500&auto=format&fit=crop&q=80",
  },
  {
    id: "frango-empanado",
    cat: "entradinhas",
    name: "Frango Empanado",
    desc: "Filezinhos de frango empanados super crocantes, acompanhados de molho.",
    price: 7.00,
    unit: "porção",
    image: "https://images.unsplash.com/photo-1562967914-608f82629710?w=500&auto=format&fit=crop&q=80",
  },
  {
    id: "tilapia-empanada",
    cat: "entradinhas",
    name: "Tilápia Empanada",
    desc: "Cubos de filé de tilápia fresca empanados com farinha crocante panko.",
    price: 7.00,
    unit: "porção",
    image: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=500&auto=format&fit=crop&q=80",
  },
  {
    id: "salgadinhos-fritos",
    cat: "entradinhas",
    name: "Salgadinhos Fritos",
    desc: "Variedade: Coxinha, pastelzinho, bolinha de queijo, quibe, croquete de costela ou linguiça e bolinha philadelphia.",
    price: 220.00,
    unit: "cento",
    image: "https://images.unsplash.com/photo-1541014741259-df5290bc5087?w=500&auto=format&fit=crop&q=80",
  },
  {
    id: "dadinho-tapioca",
    cat: "entradinhas",
    name: "Dadinho de Tapioca",
    desc: "Dadinhos dourados de tapioca com queijo coalho servidos com geleia de pimenta.",
    price: 3.50,
    unit: "unid.",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=500&auto=format&fit=crop&q=80",
  },
  {
    id: "mini-batata-recheada",
    cat: "entradinhas",
    name: "Mini Batata Recheada",
    desc: "Mini batatinhas assadas recheadas com requeijão cremoso, bacon e bacon picadinho.",
    price: 3.50,
    unit: "unid.",
    image: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=500&auto=format&fit=crop&q=80",
  },
  {
    id: "mini-pastel-brie",
    cat: "entradinhas",
    name: "Mini Pastel de Brie",
    desc: "Massa crocante com recheio cremoso de queijo brie derretido.",
    price: 6.50,
    unit: "unid.",
    image: "https://images.unsplash.com/photo-1600891964599-f61ba0e24092?w=500&auto=format&fit=crop&q=80",
  },
  {
    id: "brusqueta-minghon",
    cat: "entradinhas",
    name: "Mini Brusqueta de Mignon com Brie",
    desc: "Fatia de pão italiano com cubos de filé mignon grelhados e queijo brie gratinado.",
    price: 6.50,
    unit: "unid.",
    image: "https://images.unsplash.com/photo-1572656631137-7935297eff55?w=500&auto=format&fit=crop&q=80",
  },
  {
    id: "mini-pizza",
    cat: "entradinhas",
    name: "Mini Pizza",
    desc: "Mini pizzas artesanais nos sabores clássicos: mussarela, calabresa ou marguerita.",
    price: 5.50,
    unit: "unid.",
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=500&auto=format&fit=crop&q=80",
  },
  {
    id: "pizza-fatias",
    cat: "entradinhas",
    name: "Pizza em Fatias",
    desc: "Fatias de pizza com massa caseira super macia montada e assada na hora.",
    price: 10.00,
    unit: "fatia",
    image: "https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?w=500&auto=format&fit=crop&q=80",
  },
  {
    id: "bolinha-brie-mel",
    cat: "entradinhas",
    name: "Bolinha de Brie e Mel",
    desc: "Salgadinho fino frito recheado com queijo brie cremoso e um toque de mel silvestre.",
    price: 7.00,
    unit: "unid.",
    image: "https://images.unsplash.com/photo-1589112773905-f74a726622c5?w=500&auto=format&fit=crop&q=80",
  },
  {
    id: "batata-frita",
    cat: "entradinhas",
    name: "Batata Frita Crinkle",
    desc: "Batata frita crocante e sequinha, temperada com sal fino e alecrim.",
    price: 10.00,
    unit: "por pessoa",
    image: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=500&auto=format&fit=crop&q=80",
  },

  // Mini Porções
  {
    id: "penne",
    cat: "porcoes",
    name: "Penne Gourmet",
    desc: "Opções de molhos: na manteiga, carbonara, bolonhesa, brie com tomate confit ou quatro queijos.",
    price: 8.50,
    unit: "unid.",
    image: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=500&auto=format&fit=crop&q=80",
  },
  {
    id: "escondidinho",
    cat: "porcoes",
    name: "Escondidinho",
    desc: "Escondidinho cremoso gratinado com recheio de carne seca ou linguiça Blumenau.",
    price: 9.00,
    unit: "unid.",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=500&auto=format&fit=crop&q=80",
  },
  {
    id: "mini-quiche",
    cat: "porcoes",
    name: "Mini Quiche",
    desc: "Recheios: alho-poró com presunto parma, legumes gratinados ou frango com palmito.",
    price: 7.00,
    unit: "unid.",
    image: "https://images.unsplash.com/photo-1600891964599-f61ba0e24092?w=500&auto=format&fit=crop&q=80",
  },
  {
    id: "nhoque",
    cat: "porcoes",
    name: "Nhoque Especial",
    desc: "Molhos: mignon com gorgonzola, quatro queijos, sugo caseiro, bolonhesa ou linguiça Blumenau.",
    price: 15.00,
    unit: "unid.",
    image: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=500&auto=format&fit=crop&q=80",
  },
  {
    id: "risoto",
    cat: "porcoes",
    name: "Risoto de Arroz Arbóreo",
    desc: "Saboroso e cremoso: quatro queijos, linguiça Blumenau ou mignon com gorgonzola.",
    price: 15.00,
    unit: "unid.",
    image: "https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=500&auto=format&fit=crop&q=80",
  },
  {
    id: "fricasse",
    cat: "porcoes",
    name: "Fricassé de Frango",
    desc: "Frango desfiado cremoso gratinado com milho verde e finalizado com batata palha.",
    price: 10.00,
    unit: "unid.",
    image: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=500&auto=format&fit=crop&q=80",
  },

  // Sobremesas
  {
    id: "taca-sorvete",
    cat: "sobremesas",
    name: "Taça de Sorvete Premium",
    desc: "Taça generosa com sorvete artesanal, calda de frutas vermelhas e biscoitinho.",
    price: 15.00,
    unit: "unid.",
    image: "https://images.unsplash.com/photo-1505394033641-40c6ad1178d7?w=500&auto=format&fit=crop&q=80",
  },
  {
    id: "mini-churros",
    cat: "sobremesas",
    name: "Mini Churros Espanhol",
    desc: "Churros fininhos crocantes povilhados com açúcar e canela, acompanhados de doce de leite ou Nutella.",
    price: 7.00,
    unit: "porção",
    image: "https://images.unsplash.com/photo-1587314168485-3236d6710814?w=500&auto=format&fit=crop&q=80",
  },
  {
    id: "mini-brownie",
    cat: "sobremesas",
    name: "Mini Brownie",
    desc: "Brownie de chocolate belga molhadinho com nozes e acompanhado de sorvete de creme.",
    price: 15.00,
    unit: "porção",
    image: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=500&auto=format&fit=crop&q=80",
  },

  // Serviços Extras
  {
    id: "pessoa-servir",
    cat: "servicos",
    name: "Equipe de Garçons e Copeiras",
    desc: "Profissionais qualificados para servir os convidados. Valor varia conforme cidade e horário.",
    price: null,
    unit: null,
    image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=500&auto=format&fit=crop&q=80",
  },
  {
    id: "deslocamento",
    cat: "servicos",
    name: "Deslocamento da Equipe",
    desc: "Logística e frete para montagem e atendimento em outras cidades da região.",
    price: null,
    unit: null,
    image: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=500&auto=format&fit=crop&q=80",
  },
  {
    id: "opcoes-carrinhos",
    cat: "servicos",
    name: "Opções de Carrinhos Gourmet",
    desc: "Temos carrinhos rústicos, vintage e modernos. Sujeito à disponibilidade na data do evento.",
    price: null,
    unit: null,
    image: "https://images.unsplash.com/photo-1533900298318-6b8da08a523e?w=500&auto=format&fit=crop&q=80",
  },
  {
    id: "toldos",
    cat: "servicos",
    name: "Toldos Personalizados",
    desc: "Cobertura charmosa para montagem dos carrinhos gourmets em áreas externas.",
    price: null,
    unit: null,
    image: "https://images.unsplash.com/photo-1517457373958-b7bdd4587205?w=500&auto=format&fit=crop&q=80",
  },
];
